title: Container Instance Resource Deployment
# Sub Title shown in Application Information tab.
description: Container Instance Resource Deployment
informationalText: Container Instance Resource Deployment
schemaVersion: 1.1.0
version: "20190304"
# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708
# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.
source:
  type: marketplace
  reference: 16132843

locale: "en"
variableGroups:
  - title: "Variables"
    variables:
      - compartment_ocid
      - region
      - ad
      - name
      - container_image_url
      - shape_config_ocpus
variables:
  region:
    description: Region
    type: string
    required: false
    default: eu-zurich-1

  ad:
    type: string
    description: Availability Domain
    required: false
    default: Wfog:EU-ZURICH-1-AD-1

  container_name:
    type: string
    description: Container Instance name
    required: true

  container_image_url:
    type: string
    description: Container Image URL
    required: false
    default: busybox

  shape_config_ocpus:
    type: integer
    required: false
    default: 1

  # compartmentId dynamic dropdown, compartment_ocid present in input variables
  compartment_ocid:
    type: oci:identity:compartment:id

  env_variables:
    type: string
    visible: true
    required: false
    description: Environment Variables
    title: Environment Variables
